### ISSUE TITLE
Password shows as text in the signup page

### ISSUE THREAD

**Issue by codecustard** [chingu-voyages/v33-geckos-team-06#103]

**Comment by MandeepSingh-059** [comment]
Hey I would like to work on this, please add me

**Comment by codecustard** [comment]
Hi, thanks for the interest! Just fork the repository and submit a pull request once you're finished.... if you have any questions feel free to ask!

**Comment by MandeepSingh-059** [comment]
Made the pull request, please check if the issue is fixed : )
