### ISSUE TITLE
Design the About page

### ISSUE THREAD

**Issue by gordonruby** [chingu-voyages/v33-geckos-team-06#44]

**Comment by gordonruby** [comment]
@TheChunkyPumpkinhead If you're working on this new, can you move this under "In progress", please?

**Comment by TheChunkyPumpkinhead** [comment]
yeah

**Comment by gordonruby** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/chingu-v33-geckos-team-06-612d5511c6bf170010739ef0/issues/chingu-voyages/v33-geckos-team-06/44?planning-poker) with ZenHub @codecustard @ll560 @Yuhan-Chang-0915 @TheChunkyPumpkinhead @LynnePLex
